name: "Clickstream Bump Pod Version"

on:
  pull_request:
    branches: 
      - main
    types: [closed]

# Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  bump-pod-version:
    name: "Version bump and pushh"
    if: ${{ github.event.pull_request.merged }}
    runs-on: macos-latest
    steps:
    - run: print(ls)
      #python3 auto_version_bump.py