name: "Clickstream CI"

on: [push]

# Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  RunTests:
    name: "Unit Tests"
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Testing Clickstream
        run: bundle exec fastlane unit_test
      